# =============================================================================.
context("reserved.functions.R | vector/matrix manipulation")
# -----------------------------------------------------------------------------.
test_that(".m2v.", {
  a <- .m2v.(1:3, 1:3, nrow = 3)
  b <- c(1, 5, 9)
  expect_equal(a, b)
  a <- .m2v.(3:1, 1:3, nrow = 3)
  b <- c(3, 5, 7)
  expect_equal(a, b)
})
# -----------------------------------------------------------------------------.
test_that(".v2m.", {
  a <- .v2m.(c(1, 5, 9), nrow = 3)
  b <- cbind(1:3, 1:3)
  expect_equal(a, b)
  a <- .v2m.(c(3, 5, 7), nrow = 3)
  b <- cbind(3:1, 1:3)
  expect_equal(a, b)
})
# -----------------------------------------------------------------------------.
test_that(".to.matrix.", {
  a <- .to.matrix.(1)
  b <- matrix(1, 1)
  expect_identical(a, b)
  a <- .to.matrix.(1:2)
  b <- matrix(1:2, 1)
  expect_identical(a, b)
  a <- .to.matrix.(matrix(1:2, 1))
  b <- matrix(1:2, 1)
  expect_identical(a, b)
  a <- .to.matrix.(matrix(1:2, 2))
  b <- matrix(1:2, 2)
  expect_identical(a, b)
  a <- .to.matrix.(matrix(1:4, 2))
  b <- matrix(1:4, 2)
  expect_identical(a, b)
})
# -----------------------------------------------------------------------------.
test_that(".rep.rows.", {
  a <- .rep.rows.(1, 3)
  b <- matrix(1, 3)
  expect_identical(a, b)
  a <- .rep.rows.(1:3, 3)
  b <- matrix(1:3, 3, 3, byrow = T)
  expect_identical(a, b)
  a <- .rep.rows.(matrix(1:9, 3), 2)
  b <- matrix(1:9, 3)[1:2, ]
  expect_identical(a, b)
  a <- .rep.rows.(matrix(1:9, 3), 6)
  b <- rbind(matrix(1:9, 3), matrix(1:9, 3))
  expect_identical(a, b)
})
# -----------------------------------------------------------------------------.
test_that(".cbind.args.", {
  a <- .cbind.args.(1, 1, 1, 1, n = 2, k = 2)
  b <- matrix(1, 1, 4)
  expect_identical(a, b)
  a <- .cbind.args.(1, 1, 1, 1, n = c(1, 2), k = 2)
  b <- matrix(1, 1, 4)
  expect_identical(a, b)
  a <- .cbind.args.(1:2, 1:2, n = 2, k = 2)
  b <- matrix(1:2, 1, 4)
  expect_identical(a, b)
  a <- .cbind.args.(1:2, 1:2, n = c(1, 2), k = 2)
  b <- matrix(1:2, 1, 4)
  expect_identical(a, b)
  a <- .cbind.args.(1:4, n = 2, k = 2)
  b <- matrix(1:4, 1, 4)
  expect_identical(a, b)
  a <- .cbind.args.(1:4, n = c(1, 2), k = 2)
  b <- matrix(1:4, 1, 4)
  expect_identical(a, b)
  a <- .cbind.args.(0, 1:3, 0, 1:3, n = 2, k = 2)
  b <- cbind(0, 1:3, 0, 1:3)
  expect_identical(a, b)
  a <- .cbind.args.(0, 1:3, 0, 1:3, n = c(1, 2), k = 2)
  b <- cbind(0, 1:3, 0, 1:3)
  expect_identical(a, b)
  a <- .cbind.args.(1, 1, n = c(1, 2), k = 2)
  b <- matrix(1, 1, 2)
  expect_identical(a, b)
  a <- .cbind.args.(1:2, n = c(1, 2), k = 2)
  b <- matrix(1:2, 1, 2)
  expect_identical(a, b)
  a <- .cbind.args.(0, 1:3, n = c(1, 2), k = 2)
  b <- cbind(0, 1:3)
  expect_identical(a, b)
  a <- .cbind.args.(0, 0, matrix(1, 2, 2), n = c(1, 2), k = 2)
  b <- cbind(0, 0, matrix(1, 2, 2))
  expect_identical(a, b)
})
